var MCAT = [
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },

];

var ECAT = [
  {
    "question": "What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
];
var PMS = [
  {
    "question": "What is the scientific name of a butterfly?",
    "answers": ["Apis", "Coleoptera", "Formicidae", "Rhopalocera"],
    "correctIndex": 3
  },
];
var CSS = [
  {
    "question": "What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 3,
  },
];
var IELTS = [
  {
    "question": "What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 3,
  },
];
var General = [
  {
    "question": "What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 3,
  },
];
