var PMS = [
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "1 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "2 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "3 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "4What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "5 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "6 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "7 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "9What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "10 What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
];

var ECAT = [
  {
    "question":
        "An astronaut in space comes to know of an explosion on a nearby planet. The astronaut came to know about the explosion because:",
    "A": "The astronaut both saw and heard the explosion",
    "B": "The astronaut only heard the explosion",
    "C": "The astronaut only saw the explosion",
    "D": "The astronaut both saw and heard the explosion",
    "correctIndex": 4,
  },
  {
    "question":
        " You have 20 capacitors available with you, each of 15 F. you need a capacitor of around 1 F in a circuit. You can achieve this value by connecting:",
    "A": "15 capacitors in series",
    "B": "20 capacitors in parallel",
    "C": "20 capacitors in series",
    "D": "15 capacitors in parallel",
    "correctIndex": 4,
  },
  {
    "question":
        "When you drop a ball it accelerates downward at 9.8 m/s2. If you instead throw it downwards then its acceleration immediately after leaving your hand, assuming no air resistance, is:",
    "A": "Depends on throwing speed",
    "B": "Less than 9.8 m/s2",
    "C": "B)More than 9.8 m/s2",
    "D": "9.8 m/s2",
    "correctIndex": 3,
  },
  {
    "question": "Which one of the following is not a vector quantity?",
    "A": "Acceleration",
    "B": "Force",
    "C": "Momentum",
    "D": "None of these options",
    "correctIndex": 2,
  },
  {
    "question":
        " A tight wire is clamped at two points 2.0 m apart. It is plucked near one end. Which are three longest wavelengths present on the vibrating wire?",
    "A": "4.0 m, 2.0 m, 1 m",
    "B": "1 m, 0.5 m, 0.33 m",
    "C": "4.0 m, 2.0 m, 1.33 m",
    "D": "2.0 m, 1 m, 0.67 m",
    "correctIndex": 1,
  },
  {
    "question":
        "An ambulance moves around a large round-about, with its sirens on. For a person standing at the center of the round-about, the frequency of ambulance siren heard will be:",
    "A": "Greater than the actual siren frequency",
    "B": "Changing as the ambulance moves frequency",
    "C": "Less than actual siren frequency",
    "D": "Equal to the actual siren frequency",
    "correctIndex": 3,
  },
  {
    "question":
        " Two satellites are to be launched into space from the surface of earth. Satellite 1 has mass 10 kg and volume 1500 cm3 while satellite 2 has mass 5 kg and volume 1000 cm3 . Assume the requiredescape velocities of satellite 1 and satellite 2 are v1 and v2, respectively. The relation between v1 and v2 is:",
    "A": "v1< v",
    "B": "v1> v2",
    "C": "v1 = v2",
    "D": "Relation depends on the launch",
    "correctIndex": 1,
  },
  {
    "question":
        "A mass of a liquid of density is mixed with an equal mass of another liquid of density 3. The density f the liquid mixture is:",
    "A": "4",
    "B": "3/2",
    "C": "2",
    "D": "1",
    "correctIndex": 3,
  },
  {
    "question":
        "In an experiment, the uncertainty in the value of a resistor is 2%. Furthermore, the uncertainty in the potential difference across the same resistors is 1%. The uncertainty in the power loss in the resistor is:",
    "A": "Approximately 4%",
    "B": "Approximately 6%",
    "C": "Approximately 5%",
    "D": "Approximately 3%",
    "correctIndex": 3,
  },
  {
    "question":
        "With reference to Figure P-1, which of the following statements relating the average velocity for the complete path and the instantaneous velocity at point C is true:",
    "A": "The instantaneous velocity at C is greater than the average velocity",
    "B": "The average velocity is greater than the instantaneous velocity at C",
    "C": "The relation depends upon the mass of the toys car",
    "D": "The average velocity and the instantaneous velocity at C are equal",
    "correctIndex": 3,
  },
  {
    "question":
        "Two progressive waves of frequency 250 Hz are superimposed to produce a stationary wave in which adjacent nodes are 2 m apart. The speed of the progressive waves is:",
    "A": "500 m/sec",
    "B": "1000 m/sec",
    "C": "250 m/sec",
    "D": "125 m/sec",
    "correctIndex": 1,
  },
  {
    "question":
        "White light is directed at a diffraction grating at an angle normal to the grating starting at the normal to the grating (0o), the order of red, green and blue light in the diffracted spectrum is:",
    "A": "Blue, green, red",
    "B": "Green, blue, red",
    "C": "Red, blue, green",
    "D": "Red, green, blue",
    "correctIndex": 4,
  },
  {
    "question":
        "12.5 CoulombsA constant current of 1 ampere flows in an electrical component over a period of 5 seconds. The total charge flowing through the component over this duration is:",
    "A": "12.5 Coulombs",
    "B": "25 Coulombs",
    "C": "20 Coulombs",
    "D": "10 Coulombs",
    "correctIndex": 3,
  },
  {
    "question":
        "In an alkaline battery the anode, the cathode and electrolyte are, respectively",
    "A": "Manganese dioxide, zinc, potassium hydroxide",
    "B": "Zinc, manganese dioxide, potassium hydroxide",
    "C": "Zinc, manganese dioxide, sodium hydroxide",
    "D": "Manganese dioxide, zinc, sodium hydroxide",
    "correctIndex": 3,
  },
  {
    "question": "Lead acid batteries discharge with time because of:",
    "A": "Acid neutralizes with time",
    "B": "Both A and B",
    "C": "Deposition PbSO4 at cathode",
    "D": "Deposition of PbSO4 at anode",
    "correctIndex": 1,
  },
  {
    "question":
        "A crystal system in which all axes are equal, but none of the angle is 90`0 is:",
    "A": "Monoclinic",
    "B": "Cubic",
    "C": "Acid neutralizes with time",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question":
        "To ensure that ethanol is not used for drinking purposes, it is converted to methylated spirit by adding.",
    "A": "Only 10 % methanol",
    "B": "10 % petrol and little diesel",
    "C": "50 % alcohol",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question": "Pickle (Achaar in urdu ) when placed in the path of current.",
    "A": "Will become unfit to eat",
    "B": "Will not conduct current",
    "C": "Will conduct current",
    "D": "None of these",
    "correctIndex": 4,
  },
  {
    "question": "Steel is manufactured by open hearth process from",
    "A": "Steel scrap",
    "B": "Cast iron",
    "C": "Wrought iron",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question": "One of the following is a water soluble vitamin:",
    "A": "Vitamin A",
    "B": "Vitamin B",
    "C": "Vitamin C",
    "D": "None of these",
    "correctIndex": 4,
  },
  {
    "question": "Alkanes or paraffins are made up of:",
    "A": "Carbon, hydrogen and nitrogen only",
    "B": "Carbon and hydrogen",
    "C": "Carbon, hydrogen and oxygen only",
    "D": "None on these",
    "correctIndex": 3,
  },
  {
    "question":
        "The earth’s _____ is divided into 15 major plates of various sizes:",
    "A": "Mesosphere",
    "B": "Stratosphere",
    "C": "Lithosphere",
    "D": "None of these",
    "correctIndex": 3,
  },
  {
    "question": "When water freezes, is occupies:",
    "A": "Same amount of space",
    "B": "9% less space",
    "C": "9 % more space",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question": "At muree hills water will boil at about:",
    "A": "98oC",
    "B": "100oC",
    "C": "69oC",
    "D": "102oC",
    "correctIndex": 2,
  },
  {
    "question":
        "Uranium is best used as nuclear fuel in one of the following forms:",
    "A": "U235",
    "B": "U238",
    "C": "U237",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question": "The Beta particles are fast moving:",
    "A": "Protons",
    "B": "Neutrons",
    "C": "Electrons",
    "D": "None of these",
    "correctIndex": 3,
  },
  {
    "question":
        "One of the following countries produces maximum energy from atomic reactors: ",
    "A": "France",
    "B": "United States",
    "C": "United Kingdom",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question":
        "The severity of 2005 earthquake of Pakistan on Richter Scale was:",
    "A": "9.5",
    "B": "6.5",
    "C": "5.5",
    "D": "7.6",
    "correctIndex": 4,
  },
  {
    "question": "Vacuum tubes have been replaced by: (CSS 2013)",
    "A": "Conductors",
    "B": "Diodes",
    "C": "Transistors",
    "D": "None of these",
    "correctIndex": 3,
  },
  {
    "question": "Dacron is:",
    "A": "Polyethylene",
    "B": "Epoxy",
    "C": "Polyamide",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question": "It is a secondary plant nutrient:",
    "A": "Nitrogen",
    "B": "Phosphorus",
    "C": "Sulphur",
    "D": "None of these",
    "correctIndex": 3,
  },
  {
    "question":
        "The number of electrons of a neutral atom is automatically known if one knows the:",
    "A": "Atomic number",
    "B": "Atomic weight",
    "C": "Number of orbitals",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question": "The noble gas have:",
    "A": "No electron pair interaction",
    "B": "Non van der waal’s forces",
    "C": "High boiling points",
    "D": "Very low ionization energies",
    "correctIndex": 4,
  },
  {
    "question": "The transitions elements:",
    "A": "High pressure",
    "B": "Show variable oxidation states",
    "C": "Are all metals",
    "D": "All of the above",
    "correctIndex": 1,
  },
  {
    "question": "Potassium permanganate is:",
    "A": "An alkaline compound",
    "B": "A powerful oxidizing agent",
    "C": "A redox agent",
    "D": "A powerful reducing agent",
    "correctIndex": 4,
  },
  {
    "question":
        "The following functional group is present in both aldehydes and ketones:",
    "A": "Carbonyl",
    "B": "Oxyboron",
    "C": "None of the above",
    "D": "Hydroxyl",
    "correctIndex": 4,
  },
  {
    "question":
        "Alkanes are non-polar or weakly polar compounds that are insoluble in:",
    "A": "Uni-Polar solvent",
    "B": "Non-polar solvent",
    "C": "Polar solvent",
    "D": "None of the above",
    "correctIndex": 1,
  },
  {
    "question": "What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question":
        "Aqua reggia is found when HCl and NHO3 mixed in following ratio:",
    "A": "3 : 1",
    "B": "2 : 1",
    "C": "1 : 3",
    "D": "1 : 1",
    "correctIndex": 1,
  },
  {
    "question": "Benzene has an extraordinary stable molecule because of:",
    "A": "Regular tetrahedral structure",
    "B": "Irregular hexagonal structure",
    "C": "Localized electron cloud",
    "D": "Delocalized electron cloud",
    "correctIndex": 3,
  },
  {
    "question": "Which of the following is NOT used as fertilizer?",
    "A": "Diammonium phosphate",
    "B": "Sodium hydroxide",
    "C": "Calcium nitrate",
    "D": "Anhydrous amonia",
    "correctIndex": 4,
  },
  {
    "question":
        "Ethanol can be prepared by fermenting the following in the presence of oxygen:",
    "A": "Oil",
    "B": "Glucose",
    "C": "Protein",
    "D": "None of the above",
    "correctIndex": 2,
  },
  {
    "question":
        "The periodic table gives basic framework to study the periodic behavior of the physical and chemical properties of:",
    "A": "Elements and their inorganic compounds",
    "B": "Compounds only",
    "C": "Elements and their compounds",
    "D": "Elements only",
    "correctIndex": 2,
  },
  {
    "question": "The oxidation states of Boron are:",
    "A": "+3, +1",
    "B": "+1, -1",
    "C": "-1, -2, -3",
    "D": "+1, +2,+3",
    "correctIndex": 4,
  },
  {
    "question": "The oxidation states of carbon are:",
    "A": "+3, +1",
    "B": "+1, -1",
    "C": "-1, -2, -3",
    "D": "+1, +2,+3",
    "correctIndex": 4,
  },
  {
    "question": "The oxidation states of nitrogen are:",
    "A": "+3, +1",
    "B": "+1, -1",
    "C": "-1, -2, -3",
    "D": "+1, +2,+3",
    "correctIndex": 4,
  },
  {
    "question": "Which amino acids can be synthesized by over body:",
    "A": "Non-essential amino acids",
    "B": "Acidic amino acids",
    "C": "Essential amino acids",
    "D": "Basic amino acids",
    "correctIndex": 1,
  },
  {
    "question": "Coagulant used in water treatment:",
    "A": "Alum",
    "B": "Dolonite",
    "C": "Asbestos",
    "D": "Gypsum",
    "correctIndex": 1,
  },
  {
    "question": "Which of the following is natural polymer?",
    "A": "Polysaccharide",
    "B": "Polyethene",
    "C": "Nylon",
    "D": "Terylene",
    "correctIndex": 4,
  },
  {
    "question": "Coagulant used in water treatment:",
    "A": "Ketones gives brick red color with Fehling’s solution",
    "B": "Acetone on reduction gives primary alcohols",
    "C": "Propanal and propanone behave similarly in Tollen’s reagent",
    "D": "Formaldehyde is used in silvering of mirror",
    "correctIndex": 1,
  },
  {
    "question":
        "An astronaut in space comes to know of an explosion on a nearby planet. The astronaut came to know about the explosion because:",
    "A": "The astronaut both saw and heard the explosion",
    "B": "The astronaut only heard the explosion",
    "C": "The astronaut only saw the explosion",
    "D": "The astronaut both saw and heard the explosion",
    "correctIndex": 4,
  },
  {
    "question":
        " You have 20 capacitors available with you, each of 15 F. you need a capacitor of around 1 F in a circuit. You can achieve this value by connecting:",
    "A": "15 capacitors in series",
    "B": "20 capacitors in parallel",
    "C": "20 capacitors in series",
    "D": "15 capacitors in parallel",
    "correctIndex": 4,
  },
  {
    "question":
        "When you drop a ball it accelerates downward at 9.8 m/s2. If you instead throw it downwards then its acceleration immediately after leaving your hand, assuming no air resistance, is:",
    "A": "Depends on throwing speed",
    "B": "Less than 9.8 m/s2",
    "C": "B)More than 9.8 m/s2",
    "D": "9.8 m/s2",
    "correctIndex": 3,
  },
  {
    "question": "Which one of the following is not a vector quantity?",
    "A": "Acceleration",
    "B": "Force",
    "C": "Momentum",
    "D": "None of these options",
    "correctIndex": 2,
  },
  {
    "question":
        " A tight wire is clamped at two points 2.0 m apart. It is plucked near one end. Which are three longest wavelengths present on the vibrating wire?",
    "A": "4.0 m, 2.0 m, 1 m",
    "B": "1 m, 0.5 m, 0.33 m",
    "C": "4.0 m, 2.0 m, 1.33 m",
    "D": "2.0 m, 1 m, 0.67 m",
    "correctIndex": 1,
  },
  {
    "question":
        "An ambulance moves around a large round-about, with its sirens on. For a person standing at the center of the round-about, the frequency of ambulance siren heard will be:",
    "A": "Greater than the actual siren frequency",
    "B": "Changing as the ambulance moves frequency",
    "C": "Less than actual siren frequency",
    "D": "Equal to the actual siren frequency",
    "correctIndex": 3,
  },
  {
    "question":
        " Two satellites are to be launched into space from the surface of earth. Satellite 1 has mass 10 kg and volume 1500 cm3 while satellite 2 has mass 5 kg and volume 1000 cm3 . Assume the requiredescape velocities of satellite 1 and satellite 2 are v1 and v2, respectively. The relation between v1 and v2 is:",
    "A": "v1< v",
    "B": "v1> v2",
    "C": "v1 = v2",
    "D": "Relation depends on the launch",
    "correctIndex": 1,
  },
  {
    "question":
        "A mass of a liquid of density is mixed with an equal mass of another liquid of density 3. The density f the liquid mixture is:",
    "A": "4",
    "B": "3/2",
    "C": "2",
    "D": "1",
    "correctIndex": 3,
  },
  {
    "question":
        "In an experiment, the uncertainty in the value of a resistor is 2%. Furthermore, the uncertainty in the potential difference across the same resistors is 1%. The uncertainty in the power loss in the resistor is:",
    "A": "Approximately 4%",
    "B": "Approximately 6%",
    "C": "Approximately 5%",
    "D": "Approximately 3%",
    "correctIndex": 3,
  },
  {
    "question":
        "With reference to Figure P-1, which of the following statements relating the average velocity for the complete path and the instantaneous velocity at point C is true:",
    "A": "The instantaneous velocity at C is greater than the average velocity",
    "B": "The average velocity is greater than the instantaneous velocity at C",
    "C": "The relation depends upon the mass of the toys car",
    "D": "The average velocity and the instantaneous velocity at C are equal",
    "correctIndex": 3,
  },
  {
    "question":
        "Two progressive waves of frequency 250 Hz are superimposed to produce a stationary wave in which adjacent nodes are 2 m apart. The speed of the progressive waves is:",
    "A": "500 m/sec",
    "B": "1000 m/sec",
    "C": "250 m/sec",
    "D": "125 m/sec",
    "correctIndex": 1,
  },
  {
    "question":
        "White light is directed at a diffraction grating at an angle normal to the grating starting at the normal to the grating (0o), the order of red, green and blue light in the diffracted spectrum is:",
    "A": "Blue, green, red",
    "B": "Green, blue, red",
    "C": "Red, blue, green",
    "D": "Red, green, blue",
    "correctIndex": 4,
  },
  {
    "question":
        "12.5 CoulombsA constant current of 1 ampere flows in an electrical component over a period of 5 seconds. The total charge flowing through the component over this duration is:",
    "A": "12.5 Coulombs",
    "B": "25 Coulombs",
    "C": "20 Coulombs",
    "D": "10 Coulombs",
    "correctIndex": 3,
  },
  {
    "question":
        "In an alkaline battery the anode, the cathode and electrolyte are, respectively",
    "A": "Manganese dioxide, zinc, potassium hydroxide",
    "B": "Zinc, manganese dioxide, potassium hydroxide",
    "C": "Zinc, manganese dioxide, sodium hydroxide",
    "D": "Manganese dioxide, zinc, sodium hydroxide",
    "correctIndex": 3,
  },
  {
    "question": "Lead acid batteries discharge with time because of:",
    "A": "Acid neutralizes with time",
    "B": "Both A and B",
    "C": "Deposition PbSO4 at cathode",
    "D": "Deposition of PbSO4 at anode",
    "correctIndex": 1,
  },
  {
    "question":
        "A crystal system in which all axes are equal, but none of the angle is 90`0 is:",
    "A": "Monoclinic",
    "B": "Cubic",
    "C": "Acid neutralizes with time",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question":
        "To ensure that ethanol is not used for drinking purposes, it is converted to methylated spirit by adding.",
    "A": "Only 10 % methanol",
    "B": "10 % petrol and little diesel",
    "C": "50 % alcohol",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question": "Pickle (Achaar in urdu ) when placed in the path of current.",
    "A": "Will become unfit to eat",
    "B": "Will not conduct current",
    "C": "Will conduct current",
    "D": "None of these",
    "correctIndex": 4,
  },
  {
    "question": "Steel is manufactured by open hearth process from",
    "A": "Steel scrap",
    "B": "Cast iron",
    "C": "Wrought iron",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question": "One of the following is a water soluble vitamin:",
    "A": "Vitamin A",
    "B": "Vitamin B",
    "C": "Vitamin C",
    "D": "None of these",
    "correctIndex": 4,
  },
  {
    "question": "Alkanes or paraffins are made up of:",
    "A": "Carbon, hydrogen and nitrogen only",
    "B": "Carbon and hydrogen",
    "C": "Carbon, hydrogen and oxygen only",
    "D": "None on these",
    "correctIndex": 3,
  },
  {
    "question":
        "The earth’s _____ is divided into 15 major plates of various sizes:",
    "A": "Mesosphere",
    "B": "Stratosphere",
    "C": "Lithosphere",
    "D": "None of these",
    "correctIndex": 3,
  },
  {
    "question": "When water freezes, is occupies:",
    "A": "Same amount of space",
    "B": "9% less space",
    "C": "9 % more space",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question": "At muree hills water will boil at about:",
    "A": "98oC",
    "B": "100oC",
    "C": "69oC",
    "D": "102oC",
    "correctIndex": 2,
  },
  {
    "question":
        "Uranium is best used as nuclear fuel in one of the following forms:",
    "A": "U235",
    "B": "U238",
    "C": "U237",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question": "The Beta particles are fast moving:",
    "A": "Protons",
    "B": "Neutrons",
    "C": "Electrons",
    "D": "None of these",
    "correctIndex": 3,
  },
  {
    "question":
        "One of the following countries produces maximum energy from atomic reactors: ",
    "A": "France",
    "B": "United States",
    "C": "United Kingdom",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question":
        "The severity of 2005 earthquake of Pakistan on Richter Scale was:",
    "A": "9.5",
    "B": "6.5",
    "C": "5.5",
    "D": "7.6",
    "correctIndex": 4,
  },
  {
    "question": "Vacuum tubes have been replaced by: (CSS 2013)",
    "A": "Conductors",
    "B": "Diodes",
    "C": "Transistors",
    "D": "None of these",
    "correctIndex": 3,
  },
  {
    "question": "Dacron is:",
    "A": "Polyethylene",
    "B": "Epoxy",
    "C": "Polyamide",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question": "It is a secondary plant nutrient:",
    "A": "Nitrogen",
    "B": "Phosphorus",
    "C": "Sulphur",
    "D": "None of these",
    "correctIndex": 3,
  },
  {
    "question":
        "The number of electrons of a neutral atom is automatically known if one knows the:",
    "A": "Atomic number",
    "B": "Atomic weight",
    "C": "Number of orbitals",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question": "The noble gas have:",
    "A": "No electron pair interaction",
    "B": "Non van der waal’s forces",
    "C": "High boiling points",
    "D": "Very low ionization energies",
    "correctIndex": 4,
  },
  {
    "question": "The transitions elements:",
    "A": "High pressure",
    "B": "Show variable oxidation states",
    "C": "Are all metals",
    "D": "All of the above",
    "correctIndex": 1,
  },
  {
    "question": "Potassium permanganate is:",
    "A": "An alkaline compound",
    "B": "A powerful oxidizing agent",
    "C": "A redox agent",
    "D": "A powerful reducing agent",
    "correctIndex": 4,
  },
  {
    "question":
        "The following functional group is present in both aldehydes and ketones:",
    "A": "Carbonyl",
    "B": "Oxyboron",
    "C": "None of the above",
    "D": "Hydroxyl",
    "correctIndex": 4,
  },
  {
    "question":
        "Alkanes are non-polar or weakly polar compounds that are insoluble in:",
    "A": "Uni-Polar solvent",
    "B": "Non-polar solvent",
    "C": "Polar solvent",
    "D": "None of the above",
    "correctIndex": 1,
  },
  {
    "question": "What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question":
        "Aqua reggia is found when HCl and NHO3 mixed in following ratio:",
    "A": "3 : 1",
    "B": "2 : 1",
    "C": "1 : 3",
    "D": "1 : 1",
    "correctIndex": 1,
  },
  {
    "question": "Benzene has an extraordinary stable molecule because of:",
    "A": "Regular tetrahedral structure",
    "B": "Irregular hexagonal structure",
    "C": "Localized electron cloud",
    "D": "Delocalized electron cloud",
    "correctIndex": 3,
  },
  {
    "question": "Which of the following is NOT used as fertilizer?",
    "A": "Diammonium phosphate",
    "B": "Sodium hydroxide",
    "C": "Calcium nitrate",
    "D": "Anhydrous amonia",
    "correctIndex": 4,
  },
  {
    "question":
        "Ethanol can be prepared by fermenting the following in the presence of oxygen:",
    "A": "Oil",
    "B": "Glucose",
    "C": "Protein",
    "D": "None of the above",
    "correctIndex": 2,
  },
  {
    "question":
        "The periodic table gives basic framework to study the periodic behavior of the physical and chemical properties of:",
    "A": "Elements and their inorganic compounds",
    "B": "Compounds only",
    "C": "Elements and their compounds",
    "D": "Elements only",
    "correctIndex": 2,
  },
  {
    "question": "The oxidation states of Boron are:",
    "A": "+3, +1",
    "B": "+1, -1",
    "C": "-1, -2, -3",
    "D": "+1, +2,+3",
    "correctIndex": 4,
  },
  {
    "question": "The oxidation states of carbon are:",
    "A": "+3, +1",
    "B": "+1, -1",
    "C": "-1, -2, -3",
    "D": "+1, +2,+3",
    "correctIndex": 4,
  },
  {
    "question": "The oxidation states of nitrogen are:",
    "A": "+3, +1",
    "B": "+1, -1",
    "C": "-1, -2, -3",
    "D": "+1, +2,+3",
    "correctIndex": 4,
  },
  {
    "question": "Which amino acids can be synthesized by over body:",
    "A": "Non-essential amino acids",
    "B": "Acidic amino acids",
    "C": "Essential amino acids",
    "D": "Basic amino acids",
    "correctIndex": 1,
  },
  {
    "question": "Coagulant used in water treatment:",
    "A": "Alum",
    "B": "Dolonite",
    "C": "Asbestos",
    "D": "Gypsum",
    "correctIndex": 1,
  },
  {
    "question": "Which of the following is natural polymer?",
    "A": "Polysaccharide",
    "B": "Polyethene",
    "C": "Nylon",
    "D": "Terylene",
    "correctIndex": 4,
  },
  {
    "question": "Coagulant used in water treatment:",
    "A": "Ketones gives brick red color with Fehling’s solution",
    "B": "Acetone on reduction gives primary alcohols",
    "C": "Propanal and propanone behave similarly in Tollen’s reagent",
    "D": "Formaldehyde is used in silvering of mirror",
    "correctIndex": 1,
  },
];

var MDCAT = [
  {
    "question": "Which general formula satisfies for monosaccharides?",
    "A": "Cn(H2O)2n",
    "B": "(CH2O)n",
    "C": "C2n(H2O)n",
    "D": "Both A & C",
    "correctIndex": 4,
  },
  {
    "question":
        "The type of carbohydrate which has high molecular weight and is sparingly soluble in water",
    "A": " Monosaccharides",
    "B": "Polysaccharides",
    "C": "Maltose",
    "D": "Disaccharides",
    "correctIndex": 4,
  },
  {
    "question": "Among the following, which acid is an unsaturated acid:",
    "A": "Butyric Acid ",
    "B": "Palmitic Acid",
    "C": "Oleic Acid",
    "D": "Both B & C",
    "correctIndex": 3,
  },
  {
    "question": "Back bone of amino acids comprises of:",
    "A": " R group",
    "B": "Peptide bond",
    "C": "Amino group ",
    "D": "None of these options",
    "correctIndex": 2,
  },
  {
    "question":
        "The sequence of amino acids is major factor in which type of protein classification:",
    "A": "Primary Proteins ",
    "B": "Tertiary Proteins",
    "C": "Secondary Proteins ",
    "D": "Both B & C",
    "correctIndex": 1,
  },
  {
    "question": "What is the subunit of DNA:",
    "A": " Phosphoric Acid ",
    "B": "Nucleotide",
    "C": "Base ",
    "D": "Sugar",
    "correctIndex": 3,
  },
  {
    "question": "The type of bonding in α-Helix:",
    "A": "1,2 Glycosidic linkage",
    "B": "Disulfide bond",
    "C": "Ionic bond",
    "D": "Hydrogen bond",
    "correctIndex": 1,
  },
  {
    "question": "Enzymes has what effect on the end-product",
    "A": "They altered the product",
    "B": "No effect",
    "C": "The nature of product is completely changed",
    "D": ") End product is not obtained",
    "correctIndex": 3,
  },
  {
    "question": "Lock and Key model was explained by:",
    "A": "Koshland",
    "B": "De Duve",
    "C": "Emil Fischer",
    "D": "Drake",
    "correctIndex": 3,
  },
  {
    "question":
        "Name the inhibitors which can be neutralized by adding more substrate",
    "A": " Competitive inhibitors",
    "B": "Non-competitive inhibitors",
    "C": "Permanent Inhibitors",
    "D": "Irreversible inhibitors",
    "correctIndex": 3,
  },
  {
    "question":
        "What is the percentage of lipids in chemical composition of plasma membrane?",
    "A": "60-80%",
    "B": "40-80%",
    "C": "20-40%",
    "D": "20-60%",
    "correctIndex": 1,
  },
  {
    "question":
        "A complex network of channels extending from plasma membrane to nuclear membrane:",
    "A": "Mitochondria",
    "B": "Endoplasmic reticulum",
    "C": "Lysosomes ",
    "D": "Golgi apparatus",
    "correctIndex": 4,
  },
  {
    "question": "Group of ribosomes attached with mRNA is called:",
    "A": "Monosome",
    "B": " Polypeptide",
    "C": "Polysome",
    "D": "Lysosome",
    "correctIndex": 3,
  },
  {
    "question": "Which organelle has two Subunits:",
    "A": "Endoplasmic reticulum ",
    "B": "Nucleus",
    "C": "Ribosomes",
    "D": "Plastids",
    "correctIndex": 3,
  },
  {
    "question": "Ribosomes in prokaryotes sediments at:",
    "A": "40S ",
    "B": "80S",
    "C": "70S ",
    "D": "40S + 60S = 80S",
    "correctIndex": 1,
  },
  {
    "question": "Identify the common organelle in plant and animals:",
    "A": "Plastids ",
    "B": "Mitochondria",
    "C": "Leucoplasts",
    "D": "Chromoplasts ",
    "correctIndex": 2,
  },
  {
    "question": "Which function is associated with lysosomes:?",
    "A": "Oxidative enzymes production",
    "B": "Phagocytosis",
    "C": "Conversion of fatty acids to carbohydrates",
    "D": "both B & C",
    "correctIndex": 1,
  },
  {
    "question": "Engulfing of solid particle is termed as:",
    "A": "Engulfing",
    "B": "Phagocytosis",
    "C": "Pinocytosis",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question": "Site for the synthesis of ribosomal RNA:?",
    "A": "Nucleus",
    "B": " Nucleolus",
    "C": "Mitochondria",
    "D": "Endoplasmic Reticulum",
    "correctIndex": 2,
  },
  {
    "question":
        "Among the following which organelle has an outer membrane in it:",
    "A": "Cell membrane",
    "B": "Lysosome",
    "C": "Formicidae",
    "D": "Vacuole",
    "correctIndex": 2,
  },
  {
    "question": "Size of virus ranges in:",
    "A": "20 to 250 nm",
    "B": "25 to 250 nm",
    "C": "25 to 300 nm",
    "D": "20 to 300 nm",
    "correctIndex": 1,
  },
  {
    "question": "Reverse transcriptase is the function of:",
    "A": "Pox virus ",
    "B": "Paramyxovirus",
    "C": "HIV",
    "D": "Tobacco mosaic virus",
    "correctIndex": 2,
  },
  {
    "question":
        "When cocci form long chain of cells, the arrangement is termed as:",
    "A": "Staphylococcus",
    "B": "Streptococci",
    "C": "Sarcina ",
    "D": "Cocci",
    "correctIndex": 1,
  },
  {
    "question": "Which type of bacteria has less amount of lipids in them:",
    "A": "Gram negative bacteria",
    "B": "Positive bacteria",
    "C": "Negative bacteria",
    "D": "Gram positive bacteria",
    "correctIndex": 2,
  },
  {
    "question": "Which of the following characteristics belong to mycorrhizae:",
    "A": "Fungi and algae ",
    "B": "Fungi and lichen",
    "C": "Algae and root ",
    "D": "Fungi and root",
    "correctIndex": 1,
  },
  {
    "question": "The site where Iscaris is present:",
    "A": " Intestine",
    "B": "Stomach",
    "C": "Caecum",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question": "The intermediate host for Taenia (tape worm) is:?",
    "A": "Apis",
    "B": "Anemone",
    "C": "Pig",
    "D": "Coral",
    "correctIndex": 1,
  },
  {
    "question": "Which one is correctly matched with tail of chlorophyll:",
    "A": "Hydrophilic ",
    "B": "Coleoptera",
    "C": "Hydrophobic",
    "D": "Porphyrin ring",
    "correctIndex": 2,
  },
  {
    "question": "Graph which shows effectiveness of absorbed light is called:",
    "A": "Emission Spectrum",
    "B": "Absorption Spectrum",
    "C": "Effective Spectrum",
    "D": "Action Spectrum",
    "correctIndex": 2,
  },
  {
    "question": "What is the scientific name of a butterfly?",
    "A": "Violet light ",
    "B": "Red light",
    "C": "Green light ",
    "D": "Yellow light",
    "correctIndex": 2,
  },
  {
    "question": "Which one is correctly matched with tail of chlorophyll:",
    "A": "Hydrophilic ",
    "B": "Coleoptera",
    "C": "Hydrophobic",
    "D": "Porphyrin ring",
    "correctIndex": 2,
  },
  {
    "question": "Size of virus ranges in:",
    "A": "20 to 250 nm",
    "B": "25 to 250 nm",
    "C": "25 to 300 nm",
    "D": "20 to 300 nm",
    "correctIndex": 1,
  },
  {
    "question": "Engulfing of solid particle is termed as:",
    "A": "Engulfing",
    "B": "Phagocytosis",
    "C": "Pinocytosis",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question":
        "A complex network of channels extending from plasma membrane to nuclear membrane:",
    "A": "Mitochondria",
    "B": "Endoplasmic reticulum",
    "C": "Lysosomes ",
    "D": "Golgi apparatus",
    "correctIndex": 4,
  },
  {
    "question": "Which organelle has two Subunits:",
    "A": "Endoplasmic reticulum ",
    "B": "Nucleus",
    "C": "Ribosomes",
    "D": "Plastids",
    "correctIndex": 3,
  },
  {
    "question": "Which general formula satisfies for monosaccharides?",
    "A": "Cn(H2O)2n",
    "B": "(CH2O)n",
    "C": "C2n(H2O)n",
    "D": "Both A & C",
    "correctIndex": 4,
  },
  {
    "question": "Ribosomes in prokaryotes sediments at:",
    "A": "40S ",
    "B": "80S",
    "C": "70S ",
    "D": "40S + 60S = 80S",
    "correctIndex": 1,
  },
  {
    "question":
        "A complex network of channels extending from plasma membrane to nuclear membrane:",
    "A": "Mitochondria",
    "B": "Endoplasmic reticulum",
    "C": "Lysosomes ",
    "D": "Golgi apparatus",
    "correctIndex": 4,
  },
  {
    "question":
        "What is the percentage of lipids in chemical composition of plasma membrane?",
    "A": "60-80%",
    "B": "40-80%",
    "C": "20-40%",
    "D": "20-60%",
    "correctIndex": 1,
  },
  {
    "question":
        "Among the following which organelle has an outer membrane in it:",
    "A": "Cell membrane",
    "B": "Lysosome",
    "C": "Formicidae",
    "D": "Vacuole",
    "correctIndex": 2,
  },
  {
    "question": "The term glycolysis refers to the conversions of:",
    "A": "Pyruvate to Glucose",
    "B": "Citric Acid to CO2",
    "C": "Glucose to Pyruvate",
    "D": "Both A & B",
    "correctIndex": 1,
  },
  {
    "question": "In Citric Acid Cycle Acetyl CoA combines with ________.:",
    "A": "Glucose ",
    "B": "Rubisco",
    "C": " CO2",
    "D": "Oxaloacetate",
    "correctIndex": 2,
  },
  {
    "question": "Which one is CO2 acceptor:",
    "A": "Water",
    "B": " CO2",
    "C": "Chlorophyll",
    "D": "Rubisco",
    "correctIndex": 1,
  },
  {
    "question": "4 Name the structure from which appendix is formed:",
    "A": "Duodenum",
    "B": "Kidney",
    "C": "Caecum",
    "D": "Rectum",
    "correctIndex": 2,
  },
  {
    "question": "5 dentify the cells which secrets HCl:",
    "A": "Parietal cells ",
    "B": "Zymogen cells",
    "C": "Oxyntic cells",
    "D": "Both A and B",
    "correctIndex": 1,
  },
  {
    "question": "6 The site where all absorption takes place:",
    "A": " Large intestine ",
    "B": "Ilium",
    "C": "Small Intestine",
    "D": "Duodenum",
    "correctIndex": 2,
  },
  {
    "question": "7 In oral cavity, main function of sodium bicarbonate is:",
    "A": "To act as antiseptic ",
    "B": "To act as lubricant",
    "C": "To stabilize the pH of food",
    "D": "To make a slimy food",
    "correctIndex": 1,
  },
  {
    "question": "8 The site of gaseous exchange in humans is _?",
    "A": "Bronchioles ",
    "B": "Alveolar sacs",
    "C": "Trachea",
    "D": "Alveoli",
    "correctIndex": 2,
  },
  {
    "question":
        "9 The disease in which there is a breakdown of thin walls of alveoli:",
    "A": "Asthma",
    "B": "Tuberculosis",
    "C": "Emphysema",
    "D": "Cancer",
    "correctIndex": 2,
  },
  {
    "question": "10 The amount of CO2 exhaled from lungs during expiration:",
    "A": "4%",
    "B": "0.004",
    "C": "0.0045%",
    "D": "0.04",
    "correctIndex": 2,
  },
  {
    "question": "1 Which general formula satisfies for monosaccharides?",
    "A": "Cn(H2O)2n",
    "B": "(CH2O)n",
    "C": "C2n(H2O)n",
    "D": "Both A & C",
    "correctIndex": 4,
  },
  {
    "question":
        "2 What is the percentage of lipids in chemical composition of plasma membrane?",
    "A": "60-80%",
    "B": "40-80%",
    "C": "20-40%",
    "D": "20-60%",
    "correctIndex": 1,
  },
  {
    "question": "3 Size of virus ranges in:",
    "A": "20 to 250 nm",
    "B": "25 to 250 nm",
    "C": "25 to 300 nm",
    "D": "20 to 300 nm",
    "correctIndex": 1,
  },
  {
    "question": "4 Which one is correctly matched with tail of chlorophyll:",
    "A": "Hydrophilic ",
    "B": "Coleoptera",
    "C": "Hydrophobic",
    "D": "Porphyrin ring",
    "correctIndex": 2,
  },
  {
    "question": "5 The term glycolysis refers to the conversions of:",
    "A": "Pyruvate to Glucose",
    "B": "Citric Acid to CO2",
    "C": "Glucose to Pyruvate",
    "D": "Both A & B",
    "correctIndex": 1,
  },
  {
    "question": "6 In Citric Acid Cycle Acetyl CoA combines with ________.:",
    "A": "Glucose ",
    "B": "Rubisco",
    "C": " CO2",
    "D": "Oxaloacetate",
    "correctIndex": 2,
  },
  {
    "question": "7 Size of virus ranges in:",
    "A": "20 to 250 nm",
    "B": "25 to 250 nm",
    "C": "25 to 300 nm",
    "D": "20 to 300 nm",
    "correctIndex": 1,
  },
  {
    "question": "8 Reverse transcriptase is the function of:",
    "A": "Pox virus ",
    "B": "Paramyxovirus",
    "C": "HIV",
    "D": "Tobacco mosaic virus",
    "correctIndex": 2,
  },
  {
    "question":
        "9 A complex network of channels extending from plasma membrane to nuclear membrane:",
    "A": "Mitochondria",
    "B": "Endoplasmic reticulum",
    "C": "Lysosomes ",
    "D": "Golgi apparatus",
    "correctIndex": 4,
  },
  {
    "question":
        "10 The type of carbohydrate which has high molecular weight and is sparingly soluble in water",
    "A": " Monosaccharides",
    "B": "Polysaccharides",
    "C": "Maltose",
    "D": "Disaccharides",
    "correctIndex": 4,
  },
  {
    "question": "1 Among the following, which acid is an unsaturated acid:",
    "A": "Butyric Acid ",
    "B": "Palmitic Acid",
    "C": "Oleic Acid",
    "D": "Both B & C",
    "correctIndex": 3,
  },
  {
    "question": "2 Back bone of amino acids comprises of:",
    "A": " R group",
    "B": "Peptide bond",
    "C": "Amino group ",
    "D": "None of these options",
    "correctIndex": 2,
  },
  {
    "question": "3 Group of ribosomes attached with mRNA is called:",
    "A": "Monosome",
    "B": " Polypeptide",
    "C": "Polysome",
    "D": "Lysosome",
    "correctIndex": 3,
  },
  {
    "question": "4 Which organelle has two Subunits:",
    "A": "Endoplasmic reticulum ",
    "B": "Nucleus",
    "C": "Ribosomes",
    "D": "Plastids",
    "correctIndex": 3,
  },
  {
    "question":
        "5 When cocci form long chain of cells, the arrangement is termed as:",
    "A": "Staphylococcus",
    "B": "Streptococci",
    "C": "Sarcina ",
    "D": "Cocci",
    "correctIndex": 1,
  },
  {
    "question": "6 Which type of bacteria has less amount of lipids in them:",
    "A": "Gram negative bacteria",
    "B": "Positive bacteria",
    "C": "Negative bacteria",
    "D": "Gram positive bacteria",
    "correctIndex": 2,
  },
  {
    "question": "7 Engulfing of solid particle is termed as:",
    "A": "Engulfing",
    "B": "Phagocytosis",
    "C": "Pinocytosis",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question":
        "8 A complex network of channels extending from plasma membrane to nuclear membrane:",
    "A": "Mitochondria",
    "B": "Endoplasmic reticulum",
    "C": "Lysosomes ",
    "D": "Golgi apparatus",
    "correctIndex": 4,
  },
  {
    "question": "9 Which one is CO2 acceptor:",
    "A": "Water",
    "B": " CO2",
    "C": "Chlorophyll",
    "D": "Rubisco",
    "correctIndex": 1,
  },
  {
    "question": "10 Name the structure from which appendix is formed:",
    "A": "Duodenum",
    "B": "Kidney",
    "C": "Caecum",
    "D": "Rectum",
    "correctIndex": 2,
  },
  {
    "question":
        "1 When cocci form long chain of cells, the arrangement is termed as:",
    "A": "Staphylococcus",
    "B": "Streptococci",
    "C": "Sarcina ",
    "D": "Cocci",
    "correctIndex": 1,
  },
  {
    "question": "2 Which type of bacteria has less amount of lipids in them:",
    "A": "Gram negative bacteria",
    "B": "Positive bacteria",
    "C": "Negative bacteria",
    "D": "Gram positive bacteria",
    "correctIndex": 2,
  },
  {
    "question": "3 The term glycolysis refers to the conversions of:",
    "A": "Pyruvate to Glucose",
    "B": "Citric Acid to CO2",
    "C": "Glucose to Pyruvate",
    "D": "Both A & B",
    "correctIndex": 1,
  },
  {
    "question": "4 In Citric Acid Cycle Acetyl CoA combines with ________.:",
    "A": "Glucose ",
    "B": "Rubisco",
    "C": " CO2",
    "D": "Oxaloacetate",
    "correctIndex": 2,
  },
  {
    "question": "5 dentify the cells which secrets HCl:",
    "A": "Parietal cells ",
    "B": "Zymogen cells",
    "C": "Oxyntic cells",
    "D": "Both A and B",
    "correctIndex": 1,
  },
  {
    "question": "6 The site where all absorption takes place:",
    "A": " Large intestine ",
    "B": "Ilium",
    "C": "Small Intestine",
    "D": "Duodenum",
    "correctIndex": 2,
  },
  {
    "question": "7 Which organelle has two Subunits:",
    "A": "Endoplasmic reticulum ",
    "B": "Nucleus",
    "C": "Ribosomes",
    "D": "Plastids",
    "correctIndex": 3,
  },
  {
    "question": "8 Which general formula satisfies for monosaccharides?",
    "A": "Cn(H2O)2n",
    "B": "(CH2O)n",
    "C": "C2n(H2O)n",
    "D": "Both A & C",
    "correctIndex": 4,
  },
  {
    "question": "9 Ribosomes in prokaryotes sediments at:",
    "A": "40S ",
    "B": "80S",
    "C": "70S ",
    "D": "40S + 60S = 80S",
    "correctIndex": 1,
  },
  {
    "question": "10 Identify the common organelle in plant and animals:",
    "A": "Plastids ",
    "B": "Mitochondria",
    "C": "Leucoplasts",
    "D": "Chromoplasts ",
    "correctIndex": 2,
  },
  {
    "question": "1 Ribosomes in prokaryotes sediments at:",
    "A": "40S ",
    "B": "80S",
    "C": "70S ",
    "D": "40S + 60S = 80S",
    "correctIndex": 1,
  },
  {
    "question": "2 Identify the common organelle in plant and animals:",
    "A": "Plastids ",
    "B": "Mitochondria",
    "C": "Leucoplasts",
    "D": "Chromoplasts ",
    "correctIndex": 2,
  },
  {
    "question":
        "3 The disease in which there is a breakdown of thin walls of alveoli:",
    "A": "Asthma",
    "B": "Tuberculosis",
    "C": "Emphysema",
    "D": "Cancer",
    "correctIndex": 2,
  },
  {
    "question": "4 The amount of CO2 exhaled from lungs during expiration:",
    "A": "4%",
    "B": "0.004",
    "C": "0.0045%",
    "D": "0.04",
    "correctIndex": 2,
  },
  {
    "question":
        "5 What is the percentage of lipids in chemical composition of plasma membrane?",
    "A": "60-80%",
    "B": "40-80%",
    "C": "20-40%",
    "D": "20-60%",
    "correctIndex": 1,
  },
  {
    "question":
        "6 Among the following which organelle has an outer membrane in it:",
    "A": "Cell membrane",
    "B": "Lysosome",
    "C": "Formicidae",
    "D": "Vacuole",
    "correctIndex": 2,
  },
  {
    "question":
        "7 Graph which shows effectiveness of absorbed light is called:",
    "A": "Emission Spectrum",
    "B": "Absorption Spectrum",
    "C": "Effective Spectrum",
    "D": "Action Spectrum",
    "correctIndex": 2,
  },
  {
    "question": "8 What is the scientific name of a butterfly?",
    "A": "Violet light ",
    "B": "Red light",
    "C": "Green light ",
    "D": "Yellow light",
    "correctIndex": 2,
  },
  {
    "question": "9 Lock and Key model was explained by:",
    "A": "Koshland",
    "B": "De Duve",
    "C": "Emil Fischer",
    "D": "Drake",
    "correctIndex": 3,
  },
  {
    "question":
        "10 Name the inhibitors which can be neutralized by adding more substrate",
    "A": " Competitive inhibitors",
    "B": "Non-competitive inhibitors",
    "C": "Permanent Inhibitors",
    "D": "Irreversible inhibitors",
    "correctIndex": 3,
  },
  {
    "question": "1 The term glycolysis refers to the conversions of:",
    "A": "Pyruvate to Glucose",
    "B": "Citric Acid to CO2",
    "C": "Glucose to Pyruvate",
    "D": "Both A & B",
    "correctIndex": 1,
  },
  {
    "question": "2 In Citric Acid Cycle Acetyl CoA combines with ________.:",
    "A": "Glucose ",
    "B": "Rubisco",
    "C": " CO2",
    "D": "Oxaloacetate",
    "correctIndex": 2,
  },
  {
    "question": "3 Which one is CO2 acceptor:",
    "A": "Water",
    "B": " CO2",
    "C": "Chlorophyll",
    "D": "Rubisco",
    "correctIndex": 1,
  },
  {
    "question": "4 Name the structure from which appendix is formed:",
    "A": "Duodenum",
    "B": "Kidney",
    "C": "Caecum",
    "D": "Rectum",
    "correctIndex": 2,
  },
  {
    "question": "5 dentify the cells which secrets HCl:",
    "A": "Parietal cells ",
    "B": "Zymogen cells",
    "C": "Oxyntic cells",
    "D": "Both A and B",
    "correctIndex": 1,
  },
  {
    "question": "6 The site where all absorption takes place:",
    "A": " Large intestine ",
    "B": "Ilium",
    "C": "Small Intestine",
    "D": "Duodenum",
    "correctIndex": 2,
  },
  {
    "question": "7 In oral cavity, main function of sodium bicarbonate is:",
    "A": "To act as antiseptic ",
    "B": "To act as lubricant",
    "C": "To stabilize the pH of food",
    "D": "To make a slimy food",
    "correctIndex": 1,
  },
  {
    "question": "8 The site of gaseous exchange in humans is _?",
    "A": "Bronchioles ",
    "B": "Alveolar sacs",
    "C": "Trachea",
    "D": "Alveoli",
    "correctIndex": 2,
  },
  {
    "question":
        "9 The disease in which there is a breakdown of thin walls of alveoli:",
    "A": "Asthma",
    "B": "Tuberculosis",
    "C": "Emphysema",
    "D": "Cancer",
    "correctIndex": 2,
  },
  {
    "question": "10 The amount of CO2 exhaled from lungs during expiration:",
    "A": "4%",
    "B": "0.004",
    "C": "0.0045%",
    "D": "0.04",
    "correctIndex": 2,
  },
];

var CSS = [
  {
    "question": "When Hajj falls on a Friday it is called?",
    "A": "Hajj-e-Qiran",
    "B": "Hajj-e-Tamattu",
    "C": "Hajj-e-Ifrad",
    "D": "Hajj al-Akbar",
    "correctIndex": 4,
  },
  {
    "question":
        " The prayer offered at the shortage of rain is called  (CSS 2021)",
    "A": "Namaz-e-Khasoof",
    "B": "Namaz-e-Kasoof",
    "C": "Namaz-ul-Khauf",
    "D": "Namaz-e-Istasqa",
    "correctIndex": 4,
  },
  {
    "question":
        "Who served the Prophet Muhammad (peace be upon him) for ten years as his personal attendant? (CSS 2021)",
    "A": "Hazrat Hamzah (RA)",
    "B": "Hazrat Zaid bin Haris (RA)",
    "C": "Hazrat Anas bin Malik (RA)",
    "D": "Hazrat Khalid ibn al-Walid (RA)",
    "correctIndex": 3,
  },
  {
    "question":
        "What was the name of foster-sister of the Prophet Muhammad (PBUH)? (CSS 2021)",
    "A": "Hazrat Halimah (RA)",
    "B": "Hazrat al-Shemaa (RA)",
    "C": "Hazrat Mariah Qibtiyah (RA)",
    "D": "None of these options",
    "correctIndex": 2,
  },
  {
    "question":
        "The story of the accusation of adultery levied against Hazrat Aisha (RA), known as the event of Ifk, can also be traced in  (CSS 2021)",
    "A": "Surah 24. An-Nur (the Light)",
    "B": "Surah 28. Al-Qasas (the Stories)",
    "C": "Surah 40. Ghafar (the Forgiver)",
    "D": "Surah 48. Al-Fat’h (the Victory)",
    "correctIndex": 1,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Essay (CSS 2020)",
    "A": "Direct",
    "B": "Compose",
    "C": "Attempt",
    "D": "Effort",
    "correctIndex": 3,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Inception (CSS 2020)",
    "A": "Beginning",
    "B": "Unending",
    "C": "Incision",
    "D": "Growth",
    "correctIndex": 1,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Expatriate  (CSS 2020)",
    "A": "Infirm",
    "B": "Displaced",
    "C": "Emigrant",
    "D": "Male",
    "correctIndex": 3,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Sinister (CSS 2020)",
    "A": "Ill-famed",
    "B": "Occult",
    "C": "Malevolent",
    "D": "Sinful",
    "correctIndex": 3,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Contraption (CSS 2020)",
    "A": "Trend",
    "B": "Intrigue",
    "C": "Device",
    "D": "Sticker",
    "correctIndex": 3,
  },
  {
    "question":
        "Which province of Afghanistan accounted for 39% of the world’s illicit opium production? (as of August 2021) (CSS 2010)",
    "A": "Helmand",
    "B": "Kandahar",
    "C": "Herat",
    "D": "Kabul",
    "correctIndex": 1,
  },
  {
    "question":
        "Who served as Prime Minister of France from 2007 to 2012 under President Nicolas Sarkozy? (CSS 2010)",
    "A": "Manuel Valls",
    "B": "ernard Cazeneuve",
    "C": "Édouard Philippe",
    "D": "Jean Castex",
    "correctIndex": 4,
  },
  {
    "question": "Which is the oldest search engine of the internet? (CSS 2010)",
    "A": "Google",
    "B": "AltaVista",
    "C": "WebCrawler",
    "D": "Yahoo",
    "correctIndex": 3,
  },
  {
    "question":
        "There were five categories in Nobel Prizes in beginning. Which among the following is the sixth which was added later in 1968? (CSS 2010)",
    "A": "Literature",
    "B": "Medical Science",
    "C": "Economics",
    "D": "Peace",
    "correctIndex": 3,
  },
  {
    "question": "ANTARA is the news agency of (CSS 2010)",
    "A": "Indonesia",
    "B": "Malaysia",
    "C": "Kyrgyzstan",
    "D": "Kazakhstan",
    "correctIndex": 1,
  },
  {
    "question": "The biggest species of the cat family is: (CSS 2013)?",
    "A": "Tiger",
    "B": "Lion",
    "C": "Leopard",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question": "Which group of animals has heterogametic females? (CSS 2013)",
    "A": "Domestic fowll",
    "B": "Earthworm",
    "C": "Rabbit",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question":
        "The dominant phase of life cycle in these organisms is haploid: (CSS 2013)",
    "A": "Mosses",
    "B": "Bacteria",
    "C": "Protozoa",
    "D": "None of these",
    "correctIndex": 4,
  },
  {
    "question":
        "Which month of a calendar year can lack a new moon? (CSS 2013)",
    "A": "December",
    "B": "February",
    "C": "May",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question": "One of the following is a water soluble vitamin: (CSS 2013)",
    "A": "Vitamin A",
    "B": "Vitamin B",
    "C": "Vitamin C",
    "D": "None of these",
    "correctIndex": 4,
  },
  {
    "question": "Basha Dam is to be constructed on: (CSS 2013)",
    "A": "River Sutlaj",
    "B": "River Jhelum",
    "C": "Indus River",
    "D": "None on these",
    "correctIndex": 3,
  },
  {
    "question":
        "The earth’s _____ is divided into 15 major plates of various sizes: (CSS 2013)",
    "A": "Mesosphere",
    "B": "Stratosphere",
    "C": "Lithosphere",
    "D": "None of these",
    "correctIndex": 3,
  },
  {
    "question":
        "One of these scientists formulated basic laws of Geometry: (CSS 2013)",
    "A": "Pythagorus",
    "B": "Archimedes",
    "C": "Aristotle",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question":
        "He was the first scientist to prove that planets move around the sun: (CSS 2013)",
    "A": "Archimedes",
    "B": "Galileo Galilei",
    "C": "John Kepler",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question":
        "Uranium is best used as nuclear fuel in one of the following forms: (CSS 2013)",
    "A": "U235",
    "B": "U238",
    "C": "U237",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question": "The Beta particles are fast moving: (CSS 2013)",
    "A": "Protons",
    "B": "Neutrons",
    "C": "Electrons",
    "D": "None of these",
    "correctIndex": 3,
  },
  {
    "question":
        "One of the following countries produces maximum energy from atomic reactors: (CSS 2013)",
    "A": "France",
    "B": "United States",
    "C": "United Kingdom",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question":
        "The severity of 2005 earthquake of Pakistan on Richter Scale was: (CSS 2013)",
    "A": "9.5",
    "B": "6.5",
    "C": "5.5",
    "D": "7.6",
    "correctIndex": 4,
  },
  {
    "question": "Vacuum tubes have been replaced by: (CSS 2013)",
    "A": "Conductors",
    "B": "Diodes",
    "C": "Transistors",
    "D": "None of these",
    "correctIndex": 3,
  },
  {
    "question": "Dacron is: (CSS 2013)",
    "A": "Polyethylene",
    "B": "Epoxy",
    "C": "Polyamide",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question": "It is a secondary plant nutrient: (CSS 2013)",
    "A": "Nitrogen",
    "B": "Phosphorus",
    "C": "Sulphur",
    "D": "None of these",
    "correctIndex": 3,
  },
  {
    "question":
        "The number of electrons of a neutral atom is automatically known if one knows the: (CSS 2013)",
    "A": "Atomic number",
    "B": "Atomic weight",
    "C": "Number of orbitals",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Nabob (CSS 2016)",
    "A": "Converse",
    "B": "Frolic",
    "C": "Doubter",
    "D": "Bigwig",
    "correctIndex": 4,
  },
  {
    "question": "Select the correct SYNONYM of the given word: Pall (CSS 2016)",
    "A": "Satiate",
    "B": "Light",
    "C": "Horror",
    "D": "Carry",
    "correctIndex": 1,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Sacrosanct (CSS 2016)",
    "A": "Prayer",
    "B": "Sanctuary",
    "C": "Pious",
    "D": "Sacred",
    "correctIndex": 4,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Louche (CSS 2016)",
    "A": "Brilliant",
    "B": "Gauche",
    "C": "Fine",
    "D": "Indecent",
    "correctIndex": 4,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Stentorian (CSS 2016)",
    "A": "Loud",
    "B": "Misbegotten",
    "C": "Stealthy",
    "D": "Violent",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Loquacious (CSS 2016)",
    "A": "Talkative",
    "B": "Complicated",
    "C": "Thirsty",
    "D": "Beautiful",
    "correctIndex": 1,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Chimera (CSS 2016)",
    "A": "Chimney",
    "B": "Protest",
    "C": "Illusion",
    "D": "Panache",
    "correctIndex": 3,
  },
  {
    "question":
        " Select the correct SYNONYM of the given word: Temerity (CSS 2016)",
    "A": "Fearfulness",
    "B": "Stupidity",
    "C": "Shyness",
    "D": "Audacity",
    "correctIndex": 4,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Vociferous (CSS 2016)",
    "A": "Bountiful",
    "B": "Strident",
    "C": "Garrulous",
    "D": "Numerous",
    "correctIndex": 2,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Propinquity (CSS 2016)",
    "A": "Habit",
    "B": "Nearness",
    "C": "Capacity",
    "D": "Tendency",
    "correctIndex": 2,
  },
  {
    "question": "Slapstick : Laughter (CSS 2016)",
    "A": "Fallacy : Dismay",
    "B": "Genre : Mystery",
    "C": "Mimicry : Tears",
    "D": "Horror : Fear",
    "correctIndex": 4,
  },
  {
    "question": "Conviction : Incarceration (CSS 2016)",
    "A": "Marginalization : Intimidation",
    "B": "Radicalization : Estimation",
    "C": "Induction : Amelioration",
    "D": "Reduction : Diminution",
    "correctIndex": 4,
  },
  {
    "question": "Professor : Erudite (CSS 2016)",
    "A": "Inventor: Imaginative",
    "B": "Aviator: Licensed",
    "C": "Procrastinator: Conscientious",
    "D": "Moderator: Vicious",
    "correctIndex": 1,
  },
  {
    "question": "ANTARA is the news agency of (CSS 2010)",
    "A": "Indonesia",
    "B": "Malaysia",
    "C": "Kyrgyzstan",
    "D": "Kazakhstan",
    "correctIndex": 1,
  },
  {
    "question": "Silk Air is the airline of which country?  (CSS 2010)",
    "A": "Singapore",
    "B": "United States",
    "C": "South Korea",
    "D": "New Zealand",
    "correctIndex": 1,
  },
  {
    "question":
        "World Press Freedom Day was proclaimed by the UN General Assembly in (CSS 2010)",
    "A": "December 2000",
    "B": "December 1997",
    "C": "December 1990",
    "D": "December 1993",
    "correctIndex": 4,
  },
  {
    "question":
        "The country has the world’s largest contiguous irrigation system with almost 80 percent of the cultivated area irrigated. (CSS 2010)",
    "A": "Pakistan",
    "B": "India",
    "C": "Sri Lanka",
    "D": "Bhutan",
    "correctIndex": 1,
  },
  //copy next 50
  {
    "question": "When Hajj falls on a Friday it is called?",
    "A": "Hajj-e-Qiran",
    "B": "Hajj-e-Tamattu",
    "C": "Hajj-e-Ifrad",
    "D": "Hajj al-Akbar",
    "correctIndex": 4,
  },
  {
    "question":
        " The prayer offered at the shortage of rain is called  (CSS 2021)",
    "A": "Namaz-e-Khasoof",
    "B": "Namaz-e-Kasoof",
    "C": "Namaz-ul-Khauf",
    "D": "Namaz-e-Istasqa",
    "correctIndex": 4,
  },
  {
    "question":
        "Who served the Prophet Muhammad (peace be upon him) for ten years as his personal attendant? (CSS 2021)",
    "A": "Hazrat Hamzah (RA)",
    "B": "Hazrat Zaid bin Haris (RA)",
    "C": "Hazrat Anas bin Malik (RA)",
    "D": "Hazrat Khalid ibn al-Walid (RA)",
    "correctIndex": 3,
  },
  {
    "question":
        "What was the name of foster-sister of the Prophet Muhammad (PBUH)? (CSS 2021)",
    "A": "Hazrat Halimah (RA)",
    "B": "Hazrat al-Shemaa (RA)",
    "C": "Hazrat Mariah Qibtiyah (RA)",
    "D": "None of these options",
    "correctIndex": 2,
  },
  {
    "question":
        "The story of the accusation of adultery levied against Hazrat Aisha (RA), known as the event of Ifk, can also be traced in  (CSS 2021)",
    "A": "Surah 24. An-Nur (the Light)",
    "B": "Surah 28. Al-Qasas (the Stories)",
    "C": "Surah 40. Ghafar (the Forgiver)",
    "D": "Surah 48. Al-Fat’h (the Victory)",
    "correctIndex": 1,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Essay (CSS 2020)",
    "A": "Direct",
    "B": "Compose",
    "C": "Attempt",
    "D": "Effort",
    "correctIndex": 3,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Inception (CSS 2020)",
    "A": "Beginning",
    "B": "Unending",
    "C": "Incision",
    "D": "Growth",
    "correctIndex": 1,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Expatriate  (CSS 2020)",
    "A": "Infirm",
    "B": "Displaced",
    "C": "Emigrant",
    "D": "Male",
    "correctIndex": 3,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Sinister (CSS 2020)",
    "A": "Ill-famed",
    "B": "Occult",
    "C": "Malevolent",
    "D": "Sinful",
    "correctIndex": 3,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Contraption (CSS 2020)",
    "A": "Trend",
    "B": "Intrigue",
    "C": "Device",
    "D": "Sticker",
    "correctIndex": 3,
  },
  {
    "question":
        "Which province of Afghanistan accounted for 39% of the world’s illicit opium production? (as of August 2021) (CSS 2010)",
    "A": "Helmand",
    "B": "Kandahar",
    "C": "Herat",
    "D": "Kabul",
    "correctIndex": 1,
  },
  {
    "question":
        "Who served as Prime Minister of France from 2007 to 2012 under President Nicolas Sarkozy? (CSS 2010)",
    "A": "Manuel Valls",
    "B": "ernard Cazeneuve",
    "C": "Édouard Philippe",
    "D": "Jean Castex",
    "correctIndex": 4,
  },
  {
    "question": "Which is the oldest search engine of the internet? (CSS 2010)",
    "A": "Google",
    "B": "AltaVista",
    "C": "WebCrawler",
    "D": "Yahoo",
    "correctIndex": 3,
  },
  {
    "question":
        "There were five categories in Nobel Prizes in beginning. Which among the following is the sixth which was added later in 1968? (CSS 2010)",
    "A": "Literature",
    "B": "Medical Science",
    "C": "Economics",
    "D": "Peace",
    "correctIndex": 3,
  },
  {
    "question": "ANTARA is the news agency of (CSS 2010)",
    "A": "Indonesia",
    "B": "Malaysia",
    "C": "Kyrgyzstan",
    "D": "Kazakhstan",
    "correctIndex": 1,
  },
  {
    "question": "The biggest species of the cat family is: (CSS 2013)?",
    "A": "Tiger",
    "B": "Lion",
    "C": "Leopard",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question": "Which group of animals has heterogametic females? (CSS 2013)",
    "A": "Domestic fowll",
    "B": "Earthworm",
    "C": "Rabbit",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question":
        "The dominant phase of life cycle in these organisms is haploid: (CSS 2013)",
    "A": "Mosses",
    "B": "Bacteria",
    "C": "Protozoa",
    "D": "None of these",
    "correctIndex": 4,
  },
  {
    "question":
        "Which month of a calendar year can lack a new moon? (CSS 2013)",
    "A": "December",
    "B": "February",
    "C": "May",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question": "One of the following is a water soluble vitamin: (CSS 2013)",
    "A": "Vitamin A",
    "B": "Vitamin B",
    "C": "Vitamin C",
    "D": "None of these",
    "correctIndex": 4,
  },
  {
    "question": "Basha Dam is to be constructed on: (CSS 2013)",
    "A": "River Sutlaj",
    "B": "River Jhelum",
    "C": "Indus River",
    "D": "None on these",
    "correctIndex": 3,
  },
  {
    "question":
        "The earth’s _____ is divided into 15 major plates of various sizes: (CSS 2013)",
    "A": "Mesosphere",
    "B": "Stratosphere",
    "C": "Lithosphere",
    "D": "None of these",
    "correctIndex": 3,
  },
  {
    "question":
        "One of these scientists formulated basic laws of Geometry: (CSS 2013)",
    "A": "Pythagorus",
    "B": "Archimedes",
    "C": "Aristotle",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question":
        "He was the first scientist to prove that planets move around the sun: (CSS 2013)",
    "A": "Archimedes",
    "B": "Galileo Galilei",
    "C": "John Kepler",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question":
        "Uranium is best used as nuclear fuel in one of the following forms: (CSS 2013)",
    "A": "U235",
    "B": "U238",
    "C": "U237",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question": "The Beta particles are fast moving: (CSS 2013)",
    "A": "Protons",
    "B": "Neutrons",
    "C": "Electrons",
    "D": "None of these",
    "correctIndex": 3,
  },
  {
    "question":
        "One of the following countries produces maximum energy from atomic reactors: (CSS 2013)",
    "A": "France",
    "B": "United States",
    "C": "United Kingdom",
    "D": "None of these",
    "correctIndex": 2,
  },
  {
    "question":
        "The severity of 2005 earthquake of Pakistan on Richter Scale was: (CSS 2013)",
    "A": "9.5",
    "B": "6.5",
    "C": "5.5",
    "D": "7.6",
    "correctIndex": 4,
  },
  {
    "question": "Vacuum tubes have been replaced by: (CSS 2013)",
    "A": "Conductors",
    "B": "Diodes",
    "C": "Transistors",
    "D": "None of these",
    "correctIndex": 3,
  },
  {
    "question": "Dacron is: (CSS 2013)",
    "A": "Polyethylene",
    "B": "Epoxy",
    "C": "Polyamide",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question": "It is a secondary plant nutrient: (CSS 2013)",
    "A": "Nitrogen",
    "B": "Phosphorus",
    "C": "Sulphur",
    "D": "None of these",
    "correctIndex": 3,
  },
  {
    "question":
        "The number of electrons of a neutral atom is automatically known if one knows the: (CSS 2013)",
    "A": "Atomic number",
    "B": "Atomic weight",
    "C": "Number of orbitals",
    "D": "None of these",
    "correctIndex": 1,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Nabob (CSS 2016)",
    "A": "Converse",
    "B": "Frolic",
    "C": "Doubter",
    "D": "Bigwig",
    "correctIndex": 4,
  },
  {
    "question": "Select the correct SYNONYM of the given word: Pall (CSS 2016)",
    "A": "Satiate",
    "B": "Light",
    "C": "Horror",
    "D": "Carry",
    "correctIndex": 1,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Sacrosanct (CSS 2016)",
    "A": "Prayer",
    "B": "Sanctuary",
    "C": "Pious",
    "D": "Sacred",
    "correctIndex": 4,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Louche (CSS 2016)",
    "A": "Brilliant",
    "B": "Gauche",
    "C": "Fine",
    "D": "Indecent",
    "correctIndex": 4,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Stentorian (CSS 2016)",
    "A": "Loud",
    "B": "Misbegotten",
    "C": "Stealthy",
    "D": "Violent",
    "correctIndex": 1,
  },
  {
    "question": "8What is the scientific name of a butterfly?",
    "A": "Apis",
    "B": "Coleoptera",
    "C": "Formicidae",
    "D": "Rhopalocera",
    "correctIndex": 2,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Loquacious (CSS 2016)",
    "A": "Talkative",
    "B": "Complicated",
    "C": "Thirsty",
    "D": "Beautiful",
    "correctIndex": 1,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Chimera (CSS 2016)",
    "A": "Chimney",
    "B": "Protest",
    "C": "Illusion",
    "D": "Panache",
    "correctIndex": 3,
  },
  {
    "question":
        " Select the correct SYNONYM of the given word: Temerity (CSS 2016)",
    "A": "Fearfulness",
    "B": "Stupidity",
    "C": "Shyness",
    "D": "Audacity",
    "correctIndex": 4,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Vociferous (CSS 2016)",
    "A": "Bountiful",
    "B": "Strident",
    "C": "Garrulous",
    "D": "Numerous",
    "correctIndex": 2,
  },
  {
    "question":
        "Select the correct SYNONYM of the given word: Propinquity (CSS 2016)",
    "A": "Habit",
    "B": "Nearness",
    "C": "Capacity",
    "D": "Tendency",
    "correctIndex": 2,
  },
  {
    "question": "Slapstick : Laughter (CSS 2016)",
    "A": "Fallacy : Dismay",
    "B": "Genre : Mystery",
    "C": "Mimicry : Tears",
    "D": "Horror : Fear",
    "correctIndex": 4,
  },
  {
    "question": "Conviction : Incarceration (CSS 2016)",
    "A": "Marginalization : Intimidation",
    "B": "Radicalization : Estimation",
    "C": "Induction : Amelioration",
    "D": "Reduction : Diminution",
    "correctIndex": 4,
  },
  {
    "question": "Professor : Erudite (CSS 2016)",
    "A": "Inventor: Imaginative",
    "B": "Aviator: Licensed",
    "C": "Procrastinator: Conscientious",
    "D": "Moderator: Vicious",
    "correctIndex": 1,
  },
  {
    "question": "ANTARA is the news agency of (CSS 2010)",
    "A": "Indonesia",
    "B": "Malaysia",
    "C": "Kyrgyzstan",
    "D": "Kazakhstan",
    "correctIndex": 1,
  },
  {
    "question": "Silk Air is the airline of which country?  (CSS 2010)",
    "A": "Singapore",
    "B": "United States",
    "C": "South Korea",
    "D": "New Zealand",
    "correctIndex": 1,
  },
  {
    "question":
        "World Press Freedom Day was proclaimed by the UN General Assembly in (CSS 2010)",
    "A": "December 2000",
    "B": "December 1997",
    "C": "December 1990",
    "D": "December 1993",
    "correctIndex": 4,
  },
  {
    "question":
        "The country has the world’s largest contiguous irrigation system with almost 80 percent of the cultivated area irrigated. (CSS 2010)",
    "A": "Pakistan",
    "B": "India",
    "C": "Sri Lanka",
    "D": "Bhutan",
    "correctIndex": 1,
  },
];
